query project($owner: String!, $name: String!) {
    repository(owner: $owner, name: $name) {
        name
        languages(first: 1, orderBy: {field: SIZE, direction: DESC}) {
            edges {
                node {
                    name
                    color
                }
            }
        }
        pushedAt
    }
}
